config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
  end

  get 'site/newsfeeds'
  get "admin/index"

  post "search/index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'like'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :activities
    resources :circles
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'tag'
      get 'wall'
    end
    member do
      get 'join'
      get 'like'
      get 'show_members'
      post 'members/edit' => 'activities#edit_members'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles
  end

  resources :comments, :only => [:create, :destroy]

  resources :circles

  root :to => "site#index"

end

app/models/group.rb
class Group < ActiveRecord::Base

  validates_presence_of :name
  validates_uniqueness_of :name

  is_impressionable

  acts_as_taggable
  acts_as_commentable

  belongs_to :category

  has_many :activities, :dependent => :destroy
  has_many :second_building_applications, :class_name => "Form::SecondBuildingApplication"
  has_many :albums, :as => :imageable
  has_many :sms, :class_name => "Sms"
  has_attached_file :logo, :styles => { :medium => "300x300#", :card => "180x180#", :thumb => "64x64#" }, :default_url => "missing_:style.jpg"

  has_many :user_groups
  has_many :members,     :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Member, Constant::Member]
  has_many :planners,    :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Planner, Constant::Planner]
  has_many :managers,    :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Manager, Constant::Manager]
  has_many :admins,      :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Admin, Constant::Admin]
  has_many :followers,   :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Like, Constant::Like]
#users tend to join
  has_many :tenders,     :through => :user_groups, :source => :user, :conditions => ["user_groups.status & ? = ?", Constant::Approving, Constant::Approving]
  has_many :subscribers, :through => :user_groups, :source => :user, :conditions => ["(user_groups.status & ? = ?) || (user_groups.status & ? = ?)", Constant::Member, Constant::Member, Constant::Like, Constant::Like]


  has_many :circles, :as => :owner

  has_many :users, :through => :user_groups

  after_create :initialize_circles
  
  after_save :get_py

  def initialize_circles
    self.circles.create(:name=>I18n.t('member'),:status=> Constant::Member, :deletable=>false)
    self.circles.create(:name=>I18n.t('admin'),:status=> Constant::Admin, :deletable=>false)
  end

  def get_py
    if self.pyname!=Hz2py.do(name)
      self.pyname = Hz2py.do(name)
      save
    end
  end

  def default_circle
    circles.first
  end

  def self.daily_ranks
    ret = []
    id_arr = [1, 2, 6, 9]
    id_arr.each do |id|
      object = RankList.find_by_identify_id(id) 
      ret << object unless object.nil?
    end

    ret
  end

  def self.weekly_ranks
    ret = []
    id_arr = [10, 11, 15, 18]
    id_arr.each do |id|
      object = RankList.find_by_identify_id(id) 
      ret << object unless object.nil?
    end

    ret
  end

  def url
    logo.url(:thumb)
  end

  def admin
    admins.first || User.first
  end

  def persons
    admins | members
  end

  def person_cnt
    members.count + admins.count
  end

  def role(user)
    r = ""
    if members.include?(user)
      r = I18n.t('member')
    elsif admin == user
      r = I18n.t('group_boss')
    elsif admins.include?(user)
      r = I18n.t('admin')
    end
    r
  end

  def self.update_points
    Group.all.each do |group|
      group.points = group.pv + group.person_cnt
      group.activities.each do |activity|
        group.points += activity.points
      end
      group.save
    end
  end

  def self.recommend
    Group.order("points DESC").first(3)
  end

  def self.hot
    Group.order("points DESC").first(3)
  end

  def card
    logo.url(:card)
  end

  def thumb
    logo.url(:thumb)
  end

  def pv
    impressionist_count(:filter => :session_hash)
  end

  define_index do
    # fields
    indexes :name, :sortable => true
    indexes :introduction
    
    # attributes
    has :created_at, :updated_at

    #set_property :delta => true
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  layout "form"

  def index
    authorize! :manage, :all

    if params[:filter] == "approving"
      filter = Constant::Approving
    elsif params[:filter] == "approved"
      filter = Constant::Approved
    elsif params[:filter] == "blocked"
      filter = Constant::Blocked
    elsif params[:filter] == "rejected"
      filter = Constant::Rejected
    else
      filter = nil
    end

    if filter.nil?
      @groups = Group.paginate(:page => params[:page], :per_page => 10)
    else
      @groups = Group.where(:status => filter).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def members
    @group = Group.find(params[:id])
    authorize! :admin, @group

    @tenders = @group.tenders
    @admins  = @group.admins
    @members = @group.members
  end

  def forms
    @group = Group.find(params[:id])
    authorize! :admin, @group

    @second_buildings = @group.second_building_applications
  end

  def edit_members
    @group = Group.find(params[:id])
    authorize! :admin, @group

    member = params[:member_id]
    relation = UserGroup.f(params[:id], member)
    relation.set(params[:status][member])
    render :nothing => true
  end

  def description
    @group = Group.find(params[:id])
    authorize! :admin, @group
  end

  def introduction
    @group = Group.find(params[:id])
    authorize! :admin, @group
  end

  def history
    @group = Group.find(params[:id])
    authorize! :admin, @group
  end

  def organization
    @group = Group.find(params[:id])
    authorize! :admin, @group
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  layout :resolve_layout
  impressionist :actions => [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  private
  def resolve_layout
    case action_name
    when "index", "wall"
      "groups_index"
    when "show"
      "groups_show"
    when "new", "edit"
      "form"
    else
      "application"
    end
  end
  
  public
  # GET /groups
  # GET /groups.json

  def index
    if params[:sort] == "latest"
      sort = "created_at DESC"
    elsif params[:sort] == "founded"
      sort = "founded_at DESC"
    else
      sort = "created_at DESC"
    end

    if params[:filter] == "category"
      @groups = Category.find(params[:id]).groups.order(sort)
    elsif params[:filter] == "join"
      @groups = current_user.join_groups.order(sort)
    elsif params[:filter] == "like"
      @groups = current_user.like_groups.order(sort)
    else
      @groups = Group.where(:status => Constant::Approved).order(sort)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @more = @group.activities.count > 3
    @core = @group.comments.recent.count > 8
    @members = @group.admins + @group.members.order("user_groups.updated_at DESC").first(14)
    @mere = @group.members.count > 14

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    authorize! :admin, :site
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @form = true
    @group = Group.find(params[:id])
    authorize! :admin, @group

    case params[:q]
    when '1'
      render :action => :edit_introduction
    when '2'
      render :edit_description
    when '3'
      render :edit_history
    when '4'
      render :edit_organization
    when '5'
      redirect_to @group
    else
      render :edit
    end
  end

  # POST /groups
  # POST /groups.json
  
  def create
    authorize! :admin, :site

    @group = Group.new(params[:group])
    @group.status = Constant::Approving

    respond_to do |format|
      if @group.save
        UserGroup.create(:user => current_user, :group => @group, :status => Constant::Admin + Constant::Approved)
        format.html { redirect_to :action => 'edit', :id => @group.id, :q => 1 }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new", layout: "form" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    authorize! :admin, @group

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { 
          if params[:q].nil?
            redirect_to @group
          else
            redirect_to :action => 'edit', :id => @group.id, :q => params[:q]
          end
        }
        format.json { head :ok }
        format.js   { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    authorize! :admin, :site

    @group = Group.find(params[:id]) 
    @group.destroy 
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end

  def like
    @group = Group.find(params[:id])
    ug = @group.user_groups.find_by_user_id(current_user)
    
    if @group.followers.include?(current_user)
      ug.status &= ~Constant::Like
      ug.save
    else
      if ug
        ug.status |= Constant::Like
        ug.save
      else
        UserGroup.create!(:group_id => @group.id, :user_id => current_user.id, :status => Constant::Like)
        Event.create(:subject_type=>"User",:subject_id=>current_user.id,:action=>:like,:object_type=>"Group",:object_id=>@group.id)
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def join
    @group = Group.find(params[:id])
    ug = UserGroup.f(params[:id], current_user.id)
    
    if @group.members.include?(current_user)
      ug.status &= ~Constant::Member
      ug.save
    else
      if ug
        ug.status |= Constant::Approving
        ug.save
      else
        UserGroup.create!(:group_id => @group.id, :user_id => current_user.id, :status => Constant::Approving)
      end
    end
    respond_to do |format|
      format.js
    end
  end


  def description
    @group = Group.find(params[:id])
  end

  def history
    @group = Group.find(params[:id])
  end

  def organization
    @group = Group.find(params[:id])
  end

  def activities
    @navi = "activities/navi"
    @group = Group.find(params[:id])
    @activities = @group.activities
  end

  def comments
    @group = Group.find(params[:id])
    @comments = @group.comments.recent
  end

  def members
    @group = Group.find(params[:id])
    @members = @group.members.order("updated_at DESC")
  end

  def wall
    @groups = Group.all
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_activities.html.haml
.activities
  .header
    %span= t :activity
  .list
    - if @group.activities.empty?
      .warn= t '.warn'
    - else
      = render :partial => 'activities/card', :collection => @group.activities.last(3), :as => :activity
    .more
      = link_to (t '.more'), activities_group_path if @more

app/views/groups/_admin_panel.html.haml
.admin-panel
  .header
    %span= t '.admin'
  .list
    %ul
      %li= link_to (t '.new'), new_group_path
      %li= link_to (t '.edit'), edit_group_path
      %li= link_to (t '.activity'), new_group_activity_path(@group)
      %li= link_to (t '.members'), members_admin_group_path
      %li= link_to (t '.forms'), forms_admin_group_path
      %li= link_to (t '.sms'), sms_group_path

app/views/groups/_board.html.haml
.group.board.box
  = render :partial => 'side', :locals => { :group => group, :board => true }
  = render :partial => 'info', :locals => { :group => group }
  .clear

app/views/groups/_card.html.haml
.group.card
  = link_to (image_tag group.logo.url(:card)), group
  .info
    .top
      %span.name= link_to group.name, group
      %span.category= t group.category.name, :scope => :category
    .center
      = sanitize(group.introduction, :attributes => %w(id class style href _cke_saved_href title alt width height))   
    .bottom
      %span.founded
        = l group.founded_at
        = t '.founded'
      %span.admin
        = t :group_admin
        = link_to group.admin.name, group.admin
      %span.meta
        = t '.activities', :count => group.activities.count
        = "|"
        = t '.like', :count => group.followers.count
        = "|"
        = t '.join', :count => group.person_cnt

app/views/groups/_comments.html.haml
.comments
  .header
    %span= t :comment
    = link_to (t :comments_more), comments_group_path if @core
  .list
    = render :partial => "share/comments", :locals => { :object => @group }

app/views/groups/_like.html.haml
%span.like
  - if can? :like, group
    = link_to (t '.like'), like_group_path(group), :remote => true
  - else
    = link_to (t '.unlike'), like_group_path(group), :remote => true

app/views/groups/_members.html.haml
.members
  .header
    %span= t '.members'
    = link_to (t '.more'), members_group_path if @mere
  .box
    %ul
      - @members.each do |member|
        %li
          .avatar= image_tag member.url
          .name= link_to member.name.truncate(8), member.profile

app/views/groups/edit.html.haml
.slink
  %ul
    %li.first= t '.other'
    %li= link_to (t '.intr'), introduction_admin_group_path
    %li= link_to (t '.desc'), description_admin_group_path
    %li= link_to (t '.hist'), history_admin_group_path
    %li= link_to (t '.orga'), organization_admin_group_path
.groups.edit.box.form
  .title= t ".title"
  = render :partial => 'form', :locals => { :type => 'edit' }

app/views/groups/edit_history.html.haml
.group.form
  .title
    = t '.title'
  = form_for @group do |f|
    = hidden_field_tag 'q', '4'
    = f.cktext_area :history, :height => 300
    .button-wrapper
      = f.submit (t '.save')

app/views/groups/edit_organization.html.haml
.group.form
  .title
    = t '.title'
  = form_for @group do |f|
    = hidden_field_tag 'q', '5'
    = f.cktext_area :organization, :height => 300
    .button-wrapper
      = f.submit (t '.save')

app/views/groups/history.html.haml
.group.info-wrapper
  .back
    = link_to (t '.back'), @group
  .title
    = t '.title'
  .box
    = sanitize( @group.history, :attributes => %w(id class style href _cke_saved_href title alt width height)) 

app/views/groups/like.js.erb
$(".like").replaceWith("<%= escape_javascript(render :partial => 'groups/like', :object => @group, :as => :group ) %>");

app/views/groups/members.html.haml
.members
  .back
    = link_to (t '.back'), @group
  .title
    = t '.title', :name => @group.name
  .box
    %ul
      - @members.each do |member|
        %li
          .avatar= image_tag member.url
          .name= link_to member.name, member.profile

app/views/groups/show.html.haml
.content.show
  = render :partial => 'board', :object => @group, :as => :group
  - if can? :admin, @group
    = render :partial => 'admin_panel'
  = render :partial => 'members'
  = render :partial => 'activities'
  = render :partial => 'comments'