config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
  end

  get 'site/newsfeeds'
  get "admin/index"

  post "search/index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'like'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :activities
    resources :circles
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'tag'
      get 'wall'
    end
    member do
      get 'join'
      get 'like'
      get 'show_members'
      post 'members/edit' => 'activities#edit_members'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles
  end

  resources :comments, :only => [:create, :destroy]

  resources :circles

  root :to => "site#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  validates_presence_of :group_id
  validates_presence_of :location
  validates_presence_of :title

  acts_as_taggable
  acts_as_commentable

  is_impressionable

  belongs_to :group
  has_many :albums, :as => :imageable
  has_many :pictures, :through => :albums
  has_many :blogs, :dependent => :destroy
  has_many :user_activities
  has_many :users, :through => :user_activities
  has_attached_file :poster, :styles => { :medium => "256x360#",:card => "180x250#", :thumb => "64x64#" }, :default_url => "missing_:style.jpg"
  has_attached_file :banner, :styles => { :medium => "576x320#", :banner => "180x100#" }

  has_many :admins,      :through => :user_activities, :source => :user, :conditions => ["user_activities.status & ? = ?", Constant::Admin, Constant::Admin]
  has_many :members,     :through => :user_activities, :source => :user, :conditions => ["user_activities.status & ? = ?", Constant::Member, Constant::Member]
  has_many :followers,   :through => :user_activities, :source => :user, :conditions => ["user_activities.status & ? = ?", Constant::Like, Constant::Like]
#users tend to join
  has_many :tenders,     :through => :user_activities, :source => :user, :conditions => ["user_activities.status & ? = ?", Constant::Approving, Constant::Approving]
  has_many :subscribers, :through => :user_activities, :source => :user, :conditions => ["(user_activities.status & ? = ?) || (user_activities.status & ? = ?)", Constant::Member, Constant::Member, Constant::Like, Constant::Like]

  has_many :circles, :as => :owner

  has_many :users, :through => :user_activities

  after_save :get_py

  after_create :initialize_circles

  def initialize_circles
    self.circles.create(:name=>I18n.t('member'),:status=> Constant::Member, :deletable=>false)
    self.circles.create(:name=>I18n.t('admin'),:status=> Constant::Admin, :deletable=>false)
  end

  def default_circle
    circles.first
  end

  def related_users
    members
  end

  def get_py
    if self.pyname!=Hz2py.do(name)
      self.pyname = Hz2py.do(name)
      save
    end
  end


  def self.daily_ranks
    ret = []
    id_arr = [2, 7, 8]
    id_arr.each do |id|
      object = RankList.find_by_identify_id(id) 
      ret << object unless object.nil?
    end
    ret
  end

  def self.weekly_ranks
    ret = []
    id_arr = [11, 16, 17]
    id_arr.each do |id|
      object = RankList.find_by_identify_id(id) 
      ret << object unless object.nil?
    end

    ret
  end

  def url
    poster.url(:thumb)
  end

  def name
    title || ""
  end

  def admin
    admins.first
  end

  def persons
    admins | members
  end

  def person_cnt
    admins.count + members.count
  end

  def thumb
    poster.url(:thumb)
  end

  def card
    poster.url(:card)
  end

  def medium
    poster.url(:medium)
  end

  def self.update_points
    Activity.all.each do |activity|
      activity.points = activity.pv + activity.person_cnt
                        + activity.followers.count 
                        + activity.blogs.count * 5 
                        + activity.pictures.count * 3
    end
  end

  def self.recommend
    Activity.order("points DESC").first(3)
  end

  def self.hot
    Activity.order("points DESC").first(3)
  end

  def pv
    impressionist_count(:filter => :session_hash)
  end

  def role(user)
    r = ""
    if members.include?(user)
      r = I18n.t('activity_member')
    elsif admin == user
      r = I18n.t('activity_boss')
    elsif admins.include?(user)
      r = I18n.t('activity_admin')
    end
    r
  end

  define_index do
    indexes :title, :sortable => true
    indexed :description

    has :start_at, :end_at
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  layout :resolve_layout
  impressionist :actions => [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  private
  def resolve_layout
    case action_name
    when "index", "wall"
      "activities_index"
    when "show"
      "activities_show"
    when "new", "edit"
      "form"
    else
      "application"
    end
  end

  public
  #layout 'activities'
  # GET /activities
  # GET /activities.json
  def index

    @hots = Activity.first(5)

    if params[:sort] == "latest"
      sort = "created_at DESC"
    elsif params[:sort] == "pop"
      sort = "points DESC"
    else
      sort = "created_at DESC"
    end

    @activities = []
    if params[:filter] == "category"
      Category.find(params[:id]).groups.each do |group|
        @activities += group.activities
      end
    elsif params[:filter] == "join"
      @activities = current_user.join_activities.order(sort)
    elsif params[:filter] == "like"
      @activities = current_user.like_activities.order(sort)
    else
      @activities = Activity.order(sort).limit(50)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end


  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @group = @activity.group
    @bore = @activity.blogs.count > 4
    @pore = @activity.pictures.count > 6
    @core = @activity.comments.recent.count > 6
    if @activity.admins.include?(current_user)
      @is_admin = true
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @group = Group.find(params[:group_id])
    authorize! :admin, @group

    @activity = @group.activities.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @group = Group.find(params[:group_id])
    @activity = Activity.find(params[:id])
    authorize! :admin, @activity
  end

  # POST /activities
  # POST /activities.json
  def create
    @group = Group.find(params[:activity][:group_id])
    authorize! :admin, @group

    @activity = Activity.new(params[:activity])
    @activity.status = Constant::Approving

    respond_to do |format|
      if @activity.save
        UserActivity.create(:user => current_user, :activity => @activity, :status => Constant::Admin + Constant::Member)
        Event.create(:subject_type => "Group", :subject_id => params[:activity][:group_id], :action => "create", :object_type => "Activity", :object_id => @activity.id, :processed => false)
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])
    authorize! :admin, @activity

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated' }
        format.json { head :ok }
        format.js { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    authorize! :admin, @activity

    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end

  def like
    @activity = Activity.find(params[:id])
    ua = @activity.user_activities.find_by_user_id(current_user)
    
    if @activity.followers.include?(current_user)
      ua.status &= ~Constant::Like
      ua.save
    else
      if ua
        ua.status |= Constant::Like
        ua.save
      else
        UserActivity.create!(:activity_id => @activity.id, :user_id => current_user.id, :status => Constant::Like)
        Event.create(:subject_type=>"User",:subject_id=>current_user.id,:action=>:like,:object_type=>"Activity",:object_id=>@activity.id)
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def join
    @activity = Activity.find(params[:id])
    ua = @activity.user_activities.find_by_user_id(current_user)
    
    if @activity.members.include?(current_user)
      ua.status &= ~Constant::Member
      ua.save
    else
      if @activity.public?
        if ua
          ua.status |= Constant::Member
          ua.save
        else
          UserActivity.create!(:activity_id => @activity.id, :user_id => current_user.id, :status => Constant::Member)
        end
        Event.create(:subject_type=>"User",:subject_id => current_user.id, :action=>:join, :object_type=>"Activity", :object_id => @activity.id)
      elsif ua
        ua.status |= Constant::Approving
        ua.save
      else
        UserActivity.create!(:activity_id => @activity.id, :user_id => current_user.id, :status => Constant::Approving)
      end

    end
    respond_to do |format|
      format.js
    end
  end

  def show_members
    @activity = Activity.find(params[:id])
    @group = @activity.group
    @tenders = @activity.tenders
    @members = @activity.members
  end

  def tag_cloud
    @tags = Activity.tag_counts
  end

  def tag
    if params[:sort] == "latest"
      sort = "created_at DESC"
    elsif params[:sort] == "pop"
      sort = "points DESC"
    else
      sort = "created_at DESC"
    end

    @activities = []
    if params[:filter] == "category"
      Category.find(params[:id]).groups.each do |group|
        @activities += group.activities
      end
    elsif params[:filter] == "join"
      @activities = current_user.join_activities.order(sort)
    elsif params[:filter] == "like"
      @activities = current_user.like_activities.order(sort)
    else
      @activities = Activity.order(sort).limit(50)
    end

    @tag = ActsAsTaggableOn::Tag.find_by_name(params[:tag_name])
    @activities = @activities.find_all {|a| a.tags.include?(@tag)}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end  
  end

  def wall
    @activities = Activity.first(50)
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < ApplicationController
  layout "form"

  def index
    authorize! :manage, :all

    if params[:filter] == "approving"
      filter = Constant::Approving
    elsif params[:filter] == "approved"
      filter = Constant::Approved
    elsif params[:filter] == "blocked"
      filter = Constant::Blocked
    elsif params[:filter] == "rejected"
      filter = Constant::Rejected
    else
      filter = nil 
    end

    if filter.nil?
      @activities = Activity.paginate(:page => params[:page], :per_page => 10)
    else
      @activities = Activity.where(:status => filter).paginate(:page => params[:page], :per_page => 10)
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper

  include ActsAsTaggableOn::TagsHelper

  def stime(activity)
    if activity.start_at.to_date == activity.end_at.to_date
      t("time:",:start_time=>activity.lstart_at,:end_time=>activity.lend_at(:only_time))
    elsif activity.start_at.year == activity.end_at.year
      t("time:",:start_time=>activity.lstart_at,:end_time=>activity.lend_at)  
    else
      t("time:",:start_time=>activity.lstart_at(:default),:end_time=>activity.lend_at(:default))
    end
  end

  def is_group_member(activity, user)
    if activity.group.members.include?(user)
      t "is_group_member"
    else
      t "not_group_member"
    end
  end

  def activity_is_public(activity)
    if activity.public?
      t "public"
    else
      t "not_public"
    end
  end

  def activity_status(activity)
    case activity.status
      when Constant::Approving
        t "approving"
      when Constant::Approved
        t "approved"
      when Constant::Blocked
        t "blocked"
      when Constant::Rejected
        t"reject"
    end
  end
end

app/helpers/admin/activities_helper.rb
module Admin::ActivitiesHelper
end

app/views/activities/_board.html.haml
.activity.board.box
  = render :partial => 'side', :locals => { :activity => activity, :board => true }
  = render :partial => 'info', :locals => { :activity => activity, :board => true }

app/views/activities/_card.html.haml
.activity.card
  = link_to (image_tag activity.poster.url(:card)), activity
  .info
    .top
      %span.name= link_to activity.title, activity
    .center
      = sanitize(activity.description, :attributes => %w(id class style href _cke_saved_href title alt width height))
    .bottom
      %span.time
        = l activity.start_at, :format => :short
      %span.location
        = activity.location.truncate(20)
      %span.group
        = t '.from'
        = link_to activity.group.name.truncate(20), activity.group
      %span.meta
        = t '.like', :count => activity.followers.count
        = "|"
        = t '.join', :count => activity.person_cnt
        = "|"
        = t '.comment', :count => activity.comments.count

app/views/activities/_filter.html.haml
%ul.sort-filter{:class=> params[:filter]=='category' ? 'show-category' : ''}
  %li#filter-all= link_to (t '.all'), activities_path(:sort => params[:sort], :filter => 'all', :anchor => 'filter-all')
  %li.category
    = link_to (t '.category'), "javascript:$('.sort-filter').toggleClass('show-category');"
    %ul
      - Category.all.each do |category|
        %li{:id => 'category-'+category.id.to_s}
          = link_to category.translated_name, activities_path(:sort => params[:sort], :filter => 'category', :id => category.id, :anchor => 'category-'+category.id.to_s)
  %li#filter-like= link_to (t '.like'), activities_path(:sort => params[:sort], :filter => 'like', :anchor => 'filter-like')
  %li#filter-join= link_to (t '.join'), activities_path(:sort => params[:sort], :filter => 'join', :anchor =>'filter-join')
  %li= link_to (t '.wall'), wall_activities_path
  .clear

app/views/activities/_hot.html.haml
.hot
  .title= t '.hot'
  - @hots.each do |activity|
    = link_to (image_tag activity.card), activity

app/views/activities/_info.html.haml
.info
  .title= activity.title
  .admin
    %span.group-name= link_to activity.group.name.truncate(20), activity.group
    %span= t :host
    %span= link_to activity.admin.profile.name, activity.admin.profile
    %span= t :organize
  .tags
    = render :partial=>"share/tag_list", :locals => {:tags=>activity.tags, :controller=>:activities}
  .description
    = activity.description
  .meta
    = t '.points', :count => activity.points
    = "|"
    = t '.like', :count => activity.followers.count
    = "|"
    = t '.join', :count => activity.person_cnt
    = "|"
    = link_to (t '.blogs', :count => activity.blogs.count), activity_blogs_path(activity)
    = "|"
    = link_to (t '.pictures', :count => activity.pictures.count), activity_pictures_path(activity)
.clear

app/views/activities/_like.html.haml
%span.like
  - if can? :like, activity
    = link_to (t '.like'), like_activity_path(activity), :remote => true
  - else
    = link_to (t '.unlike'), like_activity_path(activity), :remote => true

app/views/activities/_pictures.html.haml
.pictures
  .header
    %span= t "Picture"
    = link_to (t :pictures_more), activity_pictures_path(@activity) if @pore
  - if @activity.pictures.empty?
    .box.no-content
      = t '.empty'
  - else
    .box.image_carousel
      .carousel-items
        - @activity.pictures.each do |pic|
          .image-wrap
            = link_to (image_tag pic.url(:medium))+raw("<div class='image-mask'></div>"), "#picture-ori-#{pic.id}", :class => "gallery_pics fancybox.inline", :title => "#{link_to pic.album.title,pic.album}<br />by:#{link_to pic.user.name,pic.user}<br />"+pic.remark, :"data-fancybox-group" => "gallery"
      .clear
      = link_to "", "##", :class=>"prev"
      = link_to "", "##", :class=>"next"
      .inline-hide
        - @activity.pictures.each do |pic|
          %div{:id=>"picture-ori-#{pic.id}"}=link_to image_tag(pic.url(:big)), pic

app/views/activities/_side.html.haml
.side
  .poster
    = link_to (image_tag activity.poster.url(:medium)), activity
  .role
    = activity.role(current_user) if activity.persons.include?(current_user)
  .like-join
    - unless activity.persons.include?(current_user)
      = render :partial => 'activities/like', :locals => { :activity => activity }
      = "|"
    - unless activity.admin == current_user
      = render :partial => 'activities/join', :locals => { :activity => activity }
  .location
    %span.label= t '.location'
    %span.field= activity.location
  .time
    .begin
      %span.label= t '.begin'
      %span.field= l activity.start_at, :format => :short
    .end
      %span.label= t '.end'
      %span.field= l activity.end_at, :format => :short

app/views/activities/index.html.haml
.content.index
  = render :partial => 'hot'
  = render :partial => 'filter'
  = render :partial => 'card', :collection => @activities, :as => :activity

app/views/activities/join.js.erb
$(".join").replaceWith("<%= escape_javascript(render :partial => 'activities/join', :object => @activity, :as => :activity ) %>");

app/views/activities/new.html.haml
.activity.new.box.form
  .title= t '.title'
  = render 'form'

app/views/activities/show.html.haml
.content.show
  = render :partial => 'board', :object => @activity, :as => :activity
  = render :partial => 'admin_panel' if can? :admin, @activity
  = render :partial => 'blogs'
  = render :partial => 'pictures'
  = render :partial => 'comments'

app/views/activities/tag_cloud.html.haml
- tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
  = link_to tag.name, { :action => :tag, :tag_name => tag.name}, :class => css_class

app/views/activities/wall.html.haml
.content.wall
  .hot
    .title= t '.wall'
    - @activities.each do |activity|
      = link_to (image_tag activity.poster.url(:card)), activity